/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : CrossBar1.h
**     Project     : Q8Emu_KV58_SDK12
**     Processor   : MKV58F1M0VLQ22
**     Component   : fsl_xbar
**     Version     : Component 1.2.0, Driver 01.00, CPU db: 3.50.001
**     Repository  : KSDK 1.2.0 KV5XF 1.0.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-08-23, 02:29, # CodeGen: 59
**     Contents    :
**         XBAR_DRV_Init                     - xbar_status_t XBAR_DRV_Init(xbar_state_t * xbarStatePtr);
**         XBAR_DRV_Deinit                   - void XBAR_DRV_Deinit(void);
**         XBAR_DRV_ConfigSignalConnection   - xbar_status_t XBAR_DRV_ConfigSignalConnection(xbar_input_signal_t...
**         XBAR_DRV_ConfigOutControl         - xbar_status_t XBAR_DRV_ConfigOutControl(uint32_t outIndex,const...
**         XBAR_DRV_GetEdgeDetectionStatus   - bool XBAR_DRV_GetEdgeDetectionStatus(uint32_t outIndex);
**         XBAR_DRV_ClearEdgeDetectionStatus - xbar_status_t XBAR_DRV_ClearEdgeDetectionStatus(uint32_t outIndex);
**         XBAR_DRV_InstallCallback          - xbar_status_t XBAR_DRV_InstallCallback(uint32_t outIndex,xbar_callback_t...
**         XBAR_DRV_IRQHandler               - void XBAR_DRV_IRQHandler(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file CrossBar1.h
** @version 01.00
*/         
/*!
**  @addtogroup CrossBar1_module CrossBar1 module documentation
**  @{
*/         

#ifndef __CrossBar1_H
#define __CrossBar1_H

/* Include inherited beans */
#include "clockMan1.h"
#include "Cpu.h"
#include "fsl_xbar_driver.h"

/*! @brief Device instance number */
#define FSL_CROSSBAR1 0

/*! @brief CrossBar1 state structure */
extern xbar_state_t CrossBar1_StateStruct;


#endif 
/* ifndef __CrossBar1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
